### ISSUE TITLE
可以考虑能否直接以账号密码登录

### ISSUE THREAD

**Issue by Fuzzy9876** [wangyufei2969/ScuDaKa#1]
您好，如题，使用request.post可以直接以账号密码进行登录。
`login_data = {
            'username': self.username,
            'password': self.password,
            'submit': '%E7%99%BB%E5%BD%95',
            'type': 'username_password',
            'execution': '61f952a0-a563-4c5a-a19a-b5860c3c19b4_ZXlKaGJHY2lPaUpJVXpVeE1pSjkuU0U2YzhLNTlrRG4wUVRCaDRWOEJJTGNyS3JaeTZMcVBiN05mOXJSTEJianZyT3BnZjlaRFp5OXRKdzlidC9TNEpNNllyb3N0dmk0NmFVZytnRnQ5T1FNb2ZobjJkay82UVptMmR6a0l1bFpYMDd2TEF5VGFhOWZ4Z29mVXJPMWMrMHAxdHhMcTk5NWNmMVZEU0FNUFg3ZjBwdlpCRlgyMElGQUxuRGZ1MStla1k0V0tDcmVXRDQwZEJ0VDB1ejJjRWRZQ2doL2pWT2xyd3dRWm16Tlhncis4TTBwVDF2b043UW1keXp0bVRCT2k5cGxnMGJBbmhRaWtDc0R2SFcyTkZFTlQrcGNLbTFHQ2RCakt4cGlHNWhCNGtqaGppM1UvNUx3MitCMUcyTEJvL1IwS2ZNUzcxSC9nY2szV0dMeXRkUU5GOFJmbzl0bi80MWNpRlVSdWJlTFZuRllLMWNEY01DUWtwSGRGMHBvVXAzUTliNUtxcEQydmZTdnExcEQxUXN0RTBpQVhBYk9mblJjamphU0FuWExNRGdwRTN2OWx6WDhIaDNQSi9lSGFvcnJka2pCdk5CYU5INjVzZDdxUUJKZEZrZkxaNEdFQU9oeWZaeXJjR09qb0k3czk1Y2ZXeGRTMEhDTEpoemJoU2tOeHZQMVdIT013d2ltU1hETDNjeGVwYlVtcDZUb2I4UXVWY05PeVY4c1Y1R3VPOXZDaTJDU3plVndXcFZXMDhjQ1A2N3c1ZWl1RzBWeTFVc2JOcVRwVlZpNUNFZUhpSjYvWENCYXE0bzhLWTRNanoxZm9oS1Q0Yzl1Q1V3MkM3OVZHb1BZeklYN25qVy9zandNSUNXK0c1RUtIcmV6aXlPV3B1QjZabitlaVpGdUtJV1o5SWZucCtTZloxLzZXMGZpdDlPSXlOTXpFL3p2ODdOZHBESHBiUVE4T2JqN0lFdXRodDRjb0JlYlJxR3JNR0dCR2pVcWVLWnNqbVlhWVNNcGRKMUdBNVEwU3JJMjJGSmFmZ255K0grMUg4dzdodmRyRmRMbjBEWnpmZDZqejY1Vnk3QW94SURzc1J4dER4cDdKOG1TRTAvRjRkOTlueUovTm4zVGgwMXJYVExvc0hsVnhSRzI5a2RsaysxaFBlN1hCNW1ZOGhISnFwQzVrS3h1eTgwaGIwSnFsNjBubkZGWDNxNHBJL1oxQ1pjbTBZRlhCWkM0b29iaWl5azd2dms4NWxJRisvQ1RsRkwvQWJ5RjZKWVQ3U21xbkpTdlFhM2k5T0hyVUY1eE53Sm5TMkRYakVqSTh4aVozM1UvcUFCTlZyQWR2Wllaak5wVVhCc0lhR3RCWTl3TkE3UkYrTE5OdG5kRTVvZ0ZQeE9GS2NCWDlJTWlLcnNyZXJzOHRMbUQzcjVUZUt4d1NveUR2S3FIcEhYZ1BJWSsyczJVK2tYL1hLZ1JaMW9IbU5GVjVRRkRlNGgvZTRRR2o4KzZpZFRZUlBLeWNWSTNuR0FmZ0FXTnBTelQraDhLYXA5aGwvWFBNWndyeUxlQXhva2NzQTkvL3NydUl3d0NaZmFaclRYdGVhSHZiSE5xOXkxeGtUZ1lCK0YvYU8zUnNKemtQZmphMWUxcTNkREF4UE5uNmJIMkIzNFF4M2wzYStoaXNMc1pWNUZYSGhrTWR0VHlGdFZOSWcvMG90Z1RZVVl5UnJRY0hJUUg2ZmpkalRtckozdUNId2JHM2k5WjhNSiszLzJuV3lLeDRjM001a3ZDMzlQTFo0VnZXZE5mSnFVMmc5ZSt0SW1RMkFwYTlpb2M1S1FJMEVxTkZHd2Y5WG1kazhuZEVVdGVpMTdYVElJTHpuZXFxbFBQSTVLdmwwVG1YNzZvcGxFV3duL0JMdlcvTWd2SWRsMHZQc1ErYkp1MFBKd21KbGJwcHliRDk0bFN0dVJSYUxIdmVYKzFGRWIrZmF4MG9wZkQvMFV0OVhPRFZuR2tSeTg1Q3VCSGZpOUM1NFJ6MHBDQlJaR1BHT2lEb05aYndWSytKcW0zUGpiSzRNbmxxTlRyMVFha0YrYWljamV5L212K2h4cWsralIxMmRPaEZWTk1PQm05eVZLM2lXNlQ1U1hKQjFOYnhVSXRLcjRRaDZPOXk5VmJWOGdHcVNJZmUzU1ZtMlR2a2tzUDlURm9SUnpwMGY2RXY0MHJaSk9TdlhUQ1cwUkxYZ0VvK25rNkJWQjBhdEJXSzFRVks4bFYzRTRXN29MckkvWFlrNWFHMkJ5K1o0YmxwN3FCd3EzVmRsOEdtYnRMSGNGUW13SFlma2RQdHp3Z3UzeThaN3cxc2U0YklwNmgzUzZxbk0zeGQ4QmZaNDdCTmlkQkJ4ZWFoSktKdmN6bEhyRDRlRjZlNllubGMyVXRVZHZmcFIzVVZFY3RrNWc1Y3VtTTBpZUd0WUwwNlpoQUV5SGRnWGFWdUFwQUhOV2kwSWgxclN1ZDhrVEdyYXNTZWgzOTRiSjNVM1hvNUlFdStDdlc1T0hjeDNJZ0dGa1gwN0RSclNjbjhkNHc1eEx1R25YVlZZeXhkMHVyTmQ0T2RqTVAyUDJlMGRoRlhmY2VvSGMvODk5RWNKM05lNHgyeWZuTFV5WGc1NnM2blBiWWJOTTFMd01XdWdNYUNhUzd6S2NSWFZmUGwvS0M3bDJtWUhCQTFzNmYyMWcxQnAwK2cyMXBpc2xqSlNiVVFXa3VxS0FJR2tNQmZLZ2JkQW4wQlJhMkJtZ3FyTEVMUUw3THJJS0RiUXMvZ0d1aUpCSWhUQjcrNDdyK254cjRWdU9iNWVGRW5qRzArR2kwS2FoUVpuZHpPQzFZMzZqcXc4ZkJnSXJ4UWpMdmJLVnlsTUg0dnQwNEp6Z3lJdUN2eWc5ZE9QTUhrVVdBKzhBdFNYK0dIekVzeHVYZ0RROEFwSE5rSWw1czNJVk5XUTlwMmJKZjlDc3pFbHFEZFNBM3ROdkx1K2paeFViQm1Ia0JvTUtXNWh1QXZmTEZnbU9BOGVDQWFySkJ4b1dLR3lrWlBnMy8vaWNhYjdkRlNKOHNjRmdSS1hKZHhSaDgwUmJRbGZSTVFENHFFMzFhSDhZQ1k5S3VnUGtHTkRDUEJQRW5qblk0aWJDSW5pUUFJWjIwYVh3U0RBZXdWc09SQVVMVy9rUDk4R040eThrdUhURFBkVGtGYksrQTJhdDYvRng3OGx2MDljaEM0eVVqcVJNVVRxblNpTEtBdnJsMHVTNzFTVXVnWitYN3p1YkNRYWUrbVpqcHp4ejNpMUoveVY3YVZoVXBzQmZ6ZmVsQkxseW5EWUtSVGFXS05UTjBTdjJxTVZtSDc4RU05czdjM1MrRGhnZWRHV2ZlMk92TEZRU01BR0hDQnhFZmZqNG15RmdnQjZrZFZGczJTaTNjL2M0enc3Tmk2ZEtHaExvQmY2dWdJcGx6NU53VVNHRmEySzlYZGNCd002YU1WMkxZeWJPU1V2NTJ3V2ZVNnpsNklieDM3Ulh4R2QzMUNtSUhWTlFmZTVScDZlUklqVEtLa1pFd3BxVEcrOVV5OHdxQTMzZktiN0F0MFh3bEJyMTJNOW0xTUoreVBYWTN5TGxzRDNpb2N4LzA3Z0lCajVrc2FrUm91S3VDRkJyaXZINWFtN0ZZNlpjbjkxRkVIdjhnQ2toUGRWbFRUcWpzcHd6VHBKV1BtTjlaYnd4K3gxSWxCV2pxRlhxcU5WbVJLanIvdjZLUG1COUFRSnZ6cVdUOVEzNW9QbHFYZmpTWENPYVVFTVBYZVpzbVdBZHhtTEJKZENFMVlCTmhYdjB5S2xOd1JFa2Q0MTh6dE5wa0p0ZkhadnhQM0F2VnIyYS9BOUdVZ2svekh4YVBvd2pkaHh6MVVhUkJlYW1IdjdseWNHR1pBUWVlNnI1QlVhRUdpS1dhYzNoaWRUdzdOWGZBMHZpV3VPeDA2UnlpOWIxTUtxWXZSSzlNZ3FTUkh1dGU5R0F2M3dDUnFjNEJxSnVyb2l1WEtQNmpZVVZQOGZ4RFBoMlFQRkVOeGp1eUJ2WlVsZkhudDNsTTBTWUpEN1lQcE9sNERRMzJOYkxyeUoxU2xJdTNzVkZscmU2aUtQbG0yaFFRM1pSZ3lWRDV6czNwZHpOZlAzQklPZk9vSG1lNU9GMG1hdG50QVpYek9LKzlPUXlIUkpJRk05bUVsSDgvZDd3c0R3MUFyTk9IMURqUTFEeWR1cFR5RmJkN1lHTk9SOFNCZFFXOUF1RVNTZWdqNnRRd2I1YUZua0wxOWc5OW4xdWpnRWxrQm9lZ1RBYzZ5NWl6L1drSWVzbkdXc2dOQmpwMlh4Wjh5bmI1VnU2VHB5NTI0TWJzODF5cyt5bXhPNTJva0c1MGN1cEJHV3B1dzJRRlhWbDRvQVcvZHRtMWxPdTNNYmpxallwbzdlRy91d0gxSnRzTTJwK0JvN0tmazhORXZ3Wm9XTCtrQXRWaVFhY1RWZmZsUlR5VnFKc2Qrd2hleHlNZE54bTl1eWhxSElQUEFOTVVadEtYeU80d0dDRXlFTno2TGM1cnErNk5vTllIZko0TWN5YlZnZUdqTDNoK3oxckxRcTgyc2MrbU8wUHVMNlA4Q3ZEekZMR1Q4eVVsQWxQMmkreFIrT1QwcnpTMGpNRlk4NnI5M2lUZ2pXeGtoSWtPV1UwU0VUNlQySnhqd1kxMXQ2bjFUUGt2RGM0Si9MTmVTcmJjL2d4OEEwTy81eDBtWnNycTJJTGxYMjBYc1luZXRsWkhaSUZ4TE5xZE52dHhkUmw4VVlBbEF5WE5JUyszMXlKSVJIay9NTDFub2lVQ2ZVL2dESERMMWxFOFlxYUVvaEhFUTBsRnFwNy84ckJRUzhMUjd5R3BJbE0vUHRGQkFKaUtIbjVpcGMyc2RwZzdzZjFUMVRmbXN0SEFrcVpxcW9sekVnR0NkMk5qL200QjArRXM0TTgrYlA4bG10T1JnTWs0MFQvZzVFMGtpYS8xMkM3UTB5RGFoZXAxbVQwNjBYREdrTmNlWFpMTHUvWnZEMlZTMTEvS29ubU85U0pBN1cveExpempNU2VNWGFGczYrYVNUeTZaMEUyWmpXZEhlR21pYmJWZ1lLRXJVQVRsUno4b0MxQ1pvbkEvWCtuWnJCWEJ2ZitQb3BaU0daRlVUWnUrRXBoRklGUGc5YThBSzc1M0pNbUZSb0FpRUVtTjVhd254R085YWc4MDUzSGtnNnhIVUVZblRScHFweERwdlc0Rm0yZURLbm0yV3NBa0hYNTZjcmNSUnZuVFMyYzNnOTY0WktBS0k1a1ZjTU9STE9Db1ZMajFZUzUzQThtQXVnbytEeDFXWS8vRTB1ajZFOE1kdERFTXpMN3NPVHRQUzFGRVVoblZGYmFLT0hmK1hJSGVDNG50YWR6SEVvc25OeFFDTDREMD0uYndSSGtNQjBhb1U1RnB2ZXp1MFNZWC1wSFZZVkk4TWctSW93bG1OQThQOWZVZENsSG5tWkxLWFE0S0hlZE8wMVRLblhPWVhGOV9QcGdwOFdlRENaM3c%3D',
            '_eventId': 'submit'
        }
        response = requests.post(self.url, data=login_data)`
提交地址为`https://ua.scu.edu.cn/login`
可否更新一下？谢谢

**Comment by shanzha09** [comment]
谢谢你的更新，我加上来

**Comment by Fuzzy9876** [comment]
> 谢谢你的更新，我加上来

实在抱歉，解决方式并不是像上面写的那么直接。我自己试了试，每次登录都需要携带独立的execution，但我抓包分析了一下，没办法解决如何获取execution的问题。

**Comment by shanzha09** [comment]
@somenothing 昨天我看了一下我的代码，您的方法我之前做过，账号密码登录了还是不容易获取cookies，用目前的方法最简单直接

**Comment by Fuzzy9876** [comment]
> @somenothing 昨天我看了一下我的代码，您的方法我之前做过，账号密码登录了还是不容易获取cookies，用目前的方法最简单直接

对于你这个思路来说是这样的。不过我注意到每次打卡都会自动获取上一次的记录，手动填写的很少，因此我用了selenium，可以实现使用账号密码登录。
具体实现可以看我的仓库，目前已经是成品。
